#!/usr/bin/env bash
#
# Quorum — one-time server provisioning
#
# Usage:
#   sudo bash deploy/setup.sh <domain>
#
# Prerequisites:
#   - Ubuntu 22.04 or 24.04 LTS
#   - Root or sudo access
#   - DNS A record pointing <domain> to this server's IP
#
# What this script does:
#   1. Installs Node.js 20 LTS, pnpm, nginx, PostgreSQL, certbot, build tools
#   2. Creates a 'quorum' system user
#   3. Creates the PostgreSQL database and user
#   4. Copies systemd unit files and enables them (but does not start them)
#   5. Installs nginx config with the provided domain
#   6. Creates env file stubs with DATABASE_URL and SESSION_SECRET pre-filled
#
# After running this script:
#   1. Edit /opt/quorum/deploy/env/bff.env with real secrets (KEYCLOAK, GOOGLE, etc.)
#   2. Clone/rsync the repo to /opt/quorum
#   3. Run: sudo bash /opt/quorum/deploy/deploy.sh
#   4. Obtain TLS cert: sudo certbot --nginx -d <domain>

set -euo pipefail

DOMAIN="${1:?Usage: sudo bash deploy/setup.sh <domain>}"
QUORUM_DIR="/opt/quorum"
PG_DB="quorum"
PG_USER="quorum"

echo "==> Quorum server setup for domain: ${DOMAIN}"

# ── 1. System packages ──────────────────────────────────────────────────────

echo "==> Installing system dependencies..."

# Node.js 20 LTS via NodeSource
if ! command -v node &>/dev/null || [[ "$(node --version)" != v20* ]]; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
fi

# pnpm
if ! command -v pnpm &>/dev/null; then
    npm install -g pnpm
fi

# nginx
apt-get install -y nginx

# PostgreSQL
if ! command -v psql &>/dev/null; then
    apt-get install -y postgresql postgresql-contrib
fi

# certbot for TLS
apt-get install -y certbot python3-certbot-nginx

# Build tools for native modules (better-sqlite3 needs these during pnpm install)
apt-get install -y build-essential python3

echo "==> System packages installed."

# ── 2. System user ──────────────────────────────────────────────────────────

if ! id -u quorum &>/dev/null; then
    useradd --system --shell /usr/sbin/nologin --home-dir "${QUORUM_DIR}" quorum
    echo "==> Created system user: quorum"
else
    echo "==> System user 'quorum' already exists."
fi

# ── 3. PostgreSQL database ──────────────────────────────────────────────────

echo "==> Setting up PostgreSQL..."

PG_PASSWORD="$(openssl rand -base64 32)"

# Create user (idempotent)
sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${PG_USER}'" \
  | grep -q 1 || sudo -u postgres psql -c "CREATE USER ${PG_USER} WITH PASSWORD '${PG_PASSWORD}';"

# Create database (idempotent)
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${PG_DB}'" \
  | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE ${PG_DB} OWNER ${PG_USER};"

DATABASE_URL="postgresql://${PG_USER}:${PG_PASSWORD}@127.0.0.1:5432/${PG_DB}"
echo "==> PostgreSQL database '${PG_DB}' ready."
echo "    DATABASE_URL=${DATABASE_URL}"

# ── 4. Application directory ────────────────────────────────────────────────

mkdir -p "${QUORUM_DIR}/deploy/env"
chown -R quorum:quorum "${QUORUM_DIR}"

# ── 5. Environment file stubs ──────────────────────────────────────────────

SESSION_SECRET="$(openssl rand -hex 48)"

# BFF env
if [ ! -f "${QUORUM_DIR}/deploy/env/bff.env" ]; then
    cat > "${QUORUM_DIR}/deploy/env/bff.env" <<EOF
# Quorum BFF — production environment
# Generated by setup.sh on $(date -Iseconds)

NODE_ENV=production
PORT=3001

# Database
DATABASE_URL=${DATABASE_URL}

# Keycloak OIDC — FILL THESE IN
KEYCLOAK_URL=https://snoauth.ihtsdotools.org
KEYCLOAK_REALM=snomed
KEYCLOAK_CLIENT_ID=quorum
KEYCLOAK_CLIENT_SECRET=FILL_IN
KEYCLOAK_REDIRECT_URI=https://${DOMAIN}/auth/callback

# Session
SESSION_SECRET=${SESSION_SECRET}
SESSION_COOKIE_NAME=quorum_session

# Google APIs — FILL THESE IN
GOOGLE_SERVICE_ACCOUNT_EMAIL=FILL_IN@FILL_IN.iam.gserviceaccount.com
GOOGLE_PRIVATE_KEY="FILL_IN"
GOOGLE_PROJECT_ID=FILL_IN

# Frontend origin (must match nginx server_name with scheme)
FRONTEND_ORIGIN=https://${DOMAIN}

# Discourse
DISCOURSE_URL=https://forums.snomed.org
# DISCOURSE_API_KEY=
# DISCOURSE_API_USERNAME=quorum-system
EOF
    chmod 600 "${QUORUM_DIR}/deploy/env/bff.env"
    chown quorum:quorum "${QUORUM_DIR}/deploy/env/bff.env"
    echo "==> Created ${QUORUM_DIR}/deploy/env/bff.env (edit FILL_IN values)"
else
    echo "==> ${QUORUM_DIR}/deploy/env/bff.env already exists, skipping."
    echo "    Update DATABASE_URL if needed: ${DATABASE_URL}"
fi

# Web env
if [ ! -f "${QUORUM_DIR}/deploy/env/web.env" ]; then
    cat > "${QUORUM_DIR}/deploy/env/web.env" <<EOF
# Quorum Web — production environment
# Generated by setup.sh on $(date -Iseconds)

NODE_ENV=production
PORT=3000
HOSTNAME=127.0.0.1

BFF_URL=http://127.0.0.1:3001
NEXT_PUBLIC_APP_NAME=Quorum
DISCOURSE_URL=https://forums.snomed.org
EOF
    chmod 600 "${QUORUM_DIR}/deploy/env/web.env"
    chown quorum:quorum "${QUORUM_DIR}/deploy/env/web.env"
    echo "==> Created ${QUORUM_DIR}/deploy/env/web.env"
else
    echo "==> ${QUORUM_DIR}/deploy/env/web.env already exists, skipping."
fi

# ── 6. systemd units ────────────────────────────────────────────────────────

echo "==> Installing systemd units..."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cp "${SCRIPT_DIR}/quorum-bff.service" /etc/systemd/system/quorum-bff.service
cp "${SCRIPT_DIR}/quorum-web.service" /etc/systemd/system/quorum-web.service

systemctl daemon-reload
systemctl enable quorum-bff.service
systemctl enable quorum-web.service

echo "==> systemd units installed and enabled (not yet started)."

# ── 7. nginx ────────────────────────────────────────────────────────────────

echo "==> Configuring nginx..."

mkdir -p /var/www/certbot

sed "s/QUORUM_DOMAIN/${DOMAIN}/g" "${SCRIPT_DIR}/nginx/quorum.conf" \
  > /etc/nginx/sites-available/quorum.conf

ln -sf /etc/nginx/sites-available/quorum.conf /etc/nginx/sites-enabled/quorum.conf
rm -f /etc/nginx/sites-enabled/default

nginx -t
systemctl reload nginx

echo "==> nginx configured for ${DOMAIN}."

# ── Done ────────────────────────────────────────────────────────────────────

echo ""
echo "============================================================"
echo "  Setup complete!"
echo ""
echo "  Next steps:"
echo "    1. Clone/rsync the repo to ${QUORUM_DIR}"
echo "    2. Edit ${QUORUM_DIR}/deploy/env/bff.env (fill in FILL_IN values)"
echo "    3. Run: sudo bash ${QUORUM_DIR}/deploy/deploy.sh"
echo "    4. Obtain TLS cert: sudo certbot --nginx -d ${DOMAIN}"
echo "============================================================"
